apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: spring-boot
spec:
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - name: spring-boot
        image: aurelia27/server4:v1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi